


export const COMMON_UPLOAD="COMMON_UPLOAD"
export const CREATE_UPDATE_FAQ="CREATE_UPDATE_FAQ"
export const COMMON_GET_APIS="COMMON_GET_APIS"
export const GET_FAQ="GET_FAQ"
export const GET_PRODUCTS="GET_PRODUCTS"
export const GET_SLIDER="GET_SLIDER"
export const GET_BRANCH_LOCATOR="GET_BRANCH_LOCATOR"
export const GET_PRODUCTS_LIST="GET_PRODUCTS_LIST"
export const GET_TESTIMONIAL="GET_TESTIMONIAL"
export const GET_NEWSLETTER="GET_NEWSLETTER"
export const GET_CONTACTUS="GET_CONTACTUS"
export const GET_SETTINGS_CONTACT="GET_SETTINGS_CONTACT"
export const GET_OFFLINE_POLICY="GET_OFFLINE_POLICY"
export const GET_OFFLINE_PRODUCTS="GET_OFFLINE_PRODUCTS"
export const GET_PRODUCT_SLIDER="GET_PRODUCT_SLIDER"

export const GET_CUSTOMERS_LIST="GET_CUSTOMERS_LIST"

export const CREATE_CONTACT_US="CREATE_CONTACT_US"
export const CREATE_NEWSLETTER="CREATE_NEWSLETTER"

// add customers
export const ADD_CUSTOMERS="ADD_CUSTOMERS"
export const DELETE_CUSTOMERS="DELETE_CUSTOMERS"
export const GET_CUSTOMERS="GET_CUSTOMERS"


// login 
export const USER_SIGN_IN="USER_SIGN_IN"
export const USER_SIGN_UP="USER_SIGN_UP"
export const PROFILE_UPDATE="PROFILE_UPDATE"


// form create
export const LIFE_POLICY_CREATE="LIFE_POLICY_CREATE"
export const TRAVEL_POLICY_CREATE="TRAVEL_POLICY_CREATE"
export const MOTOR_POLICY_CREATE = "MOTOR_POLICY_CREATE"
export const GET_QUESTIONS = "GET_QUESTIONS"


// dashboard
export const POLICY_ENQUIRY="POLICY_ENQUIRY"
export const MOTOR_POLICY="MOTOR_POLICY"
export const TRAVEL_POLICY="TRAVEL_POLICY"
export const SERVICE_REQUEST="SERVICE_REQUEST"
export const DELETE_SERVICE_REQUEST="DELETE_SERVICE_REQUEST"


export const USER_GET_QUOTE="USER_GET_QUOTE"
export const TRAVEL_GET_QUOTE="TRAVEL_GET_QUOTE"
export const MOTOR_GET_QUOTE="MOTOR_GET_QUOTE"
// my claimes
export const MYCLAIMES_GET__API="MYCLAIMES_GET__API"

export const USERLEAVE_LIFE_POLICY_CREATE="USERLEAVE_LIFE_POLICY_CREATE"

export const PROFILE_GET_API="PROFILE_GET_API"



// mobile
export const DASHOARD_MENU="DASHOARD_MENU"

export const EDIT_POLICY_DATA="EDIT_POLICY_DATA"
